### ISSUE TITLE
Tomahawk variants

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#1]
Currently I'm working on various tomahawks utilizing materials from vanilla, as well as some other mods. For now, I have created three new tomahawks, using some fairly common metals added by mods.

https://www.dropbox.com/s/24zry1jro2avqei/tomahawks1.zip?dl=0

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/v4645pmj37uwkdm/tomahawks2.zip?dl=0

I have now created tomahawks using vanilla materials, plus one using thaumium. I considered manasteel from botania, but, I do not think the current tomahawk textures would match well with it.

**Comment by ljfa-ag** [comment]
Nice! Well I guess Tomahawks are gonna have to wait for a while though.

**Comment by Sunconure11** [comment]
While Manasteel variants are out of my range for now due to the fact their textures are different compared to other tools from other mods, I will likely create silver and electrum variants. Remind me when tomahawks are going to be used again.

**Comment by Sunconure11** [comment]
I don't think this ever went anywhere. Closing until we find a use.
