### ISSUE TITLE
duping red cedar saplings

### ISSUE THREAD

**Issue by LabGoblin** [TeamTotemic/Totemic#10]
if you have 2 red cedar sapling and place one then proceed to break and pick it up the stack in your inventory becomes 3 instead of 2

**Comment by ljfa-ag** [comment]
Hm, doesn't happen to me. But there is a different bug with red cedar saplings that might be related and is fixed in the upcoming version. Maybe that will help.

**Comment by LabGoblin** [comment]
I'll report back after the update then

**Comment by ljfa-ag** [comment]
Is it still happening?

**Comment by LabGoblin** [comment]
i don't seem to be able to recreate it. i don't exactly remember the steps i took either though
