### ISSUE TITLE
Suggestion: Configurable ceremony music energy gain!

### ISSUE THREAD

**Issue by SirAron111** [TeamTotemic/Totemic#100]
Suggestion: Configurable ceremony music energy gain!
At the moment it’s really hard to do the ceremonies for the bald eagle and the skeleton boss when the world is set to hard mode. This makes modpack balancing a bit troublesome and makes people frustrate especially when it can lag just a tiny bit. Being able to for example set the music gain values for using certain instruments just a bit higher than standard would help allot

**Comment by demfels** [comment]
I love the totemic mod, but I do totally agree with this.  I have a modpack that I've been working on and it has been hard to get Ceremonies balanced.  They are very hard to complete for most players, and I think it gets harder in multiplayer with other people online I could be mistaken, I'm not sure.  Which if true, makes it kind of unfair for players a server playing far away from the other players online.  In most modpacks this is used as an early game stepping stone.

One suggestion I have is to allow us to configure how many wind chimes are usable.  It appears that only 3 right now are valid on any given area.
