### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sinistar26** [TeamTotemic/Totemic#109]
---- Minecraft Crash Report ----
// You're mean.

Time: 2019-08-26 20:01:51 PDT
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
    at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
    at pokefenn.totemic.init.ModBlocks.init(ModBlocks.java:53)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_751_ModBlocks_init_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 836856744 bytes (798 MB) / 1918369792 bytes (1829 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 141 mods loaded, 140 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version                  | Source                                           | Signature                                |
       |:----- |:--------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
       | LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                    | None                                     |
       | LCH   | mcp                               | 9.42                     | minecraft.jar                                    | None                                     |
       | LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                             | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | foamfixcore                       | 7.7.4                    | minecraft.jar                                    | None                                     |
       | LCH   | actuallyadditions                 | 1.12.2-r149              | ActuallyAdditions-1.12.2-r149.jar                | None                                     |
       | LCH   | afaoe                             | 1.2.2.22                 | afaoe-1.2.2.22.jar                               | None                                     |
       | LCH   | akashictome                       | 1.2-12                   | AkashicTome-1.2-12.jar                           | None                                     |
       | LCH   | aroma1997core                     | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                 | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCH   | aroma1997sdimension               | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
       | LCH   | crafttweaker                      | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                    | None                                     |
       | LCH   | astralsorcery                     | 1.10.20                  | astralsorcery-1.12.2-1.10.20.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCH   | atum                              | 2.0.12                   | Atum-1.12.2-2.0.12.jar                           | None                                     |
       | LCH   | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                            | None                                     |
       | LCH   | badwithernocookiereloaded         | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar      | None                                     |
       | LCH   | betteragriculture                 | 1.2.3                    | betteragriculture-1.12.2-1.2.3.jar               | None                                     |
       | LCH   | betterbuilderswands               | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar  | None                                     |
       | LCH   | forgelin                          | 1.8.3                    | Forgelin-1.8.3.jar                               | None                                     |
       | LCH   | betterportals                     | 0.2.6                    | betterportals-0.2.6.jar                          | None                                     |
       | LCH   | endertweaker                      | 1.1.7                    | EnderTweaker-1.12.2-1.1.7.jar                    | None                                     |
       | LCH   | jei                               | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                        | None                                     |
       | LCH   | blockdrops                        | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                      | None                                     |
       | LCH   | bonsaitrees                       | 1.1.3                    | bonsaitrees-1.1.3-b156.jar                       | None                                     |
       | LCH   | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                 | None                                     |
       | LCH   | botania                           | r1.10-361                | Botania r1.10-361.jar                            | None                                     |
       | LCH   | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
       | LCH   | chinjufumod                       | 3.2.2                    | ChinjufuMod[1.12.2]3.2.2.jar                     | None                                     |
       | LCH   | ctm                               | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
       | LCH   | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                     | None                                     |
       | LCH   | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                 | None                                     |
       | LCH   | codechickenlib                    | 3.2.3.357                | CodeChickenLib-1.12.2-3.2.3.357-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | redstoneflux                      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | cofhcore                          | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar           | None                                     |
       | LCH   | cofhworld                         | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                  | None                                     |
       | LCH   | compactdrawers                    | 1.12.2-1.0.5.123         | CompactDrawers-1.12.2-1.0.5.123.jar              | None                                     |
       | LCH   | cookingforblockheads              | 6.4.71                   | CookingForBlockheads_1.12.2-6.4.71.jar           | None                                     |
       | LCH   | craftingtweaks                    | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                  | None                                     |
       | LCH   | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.19.jar                    | None                                     |
       | LCH   | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                    | None                                     |
       | LCH   | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                        | None                                     |
       | LCH   | cyclopscore                       | 1.5.0                    | CyclopsCore-1.12.2-1.5.0.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | eleccore                          | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                      | None                                     |
       | LCH   | endercore                         | 1.12.2-0.5.65            | EnderCore-1.12.2-0.5.65.jar                      | None                                     |
       | LCH   | thermalfoundation                 | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | thermalexpansion                  | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | enderio                           | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | mcjtylib_ng                       | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                          | None                                     |
       | LCH   | deepresonance                     | 1.8.0                    | deepresonance-1.12-1.8.0.jar                     | None                                     |
       | LCH   | easyretrogen                      | 5.0.1                    | EasyRetrogen-1.12.2-5.0.1-universal.jar          | None                                     |
       | LCH   | elevatorid                        | 1.3.11                   | ElevatorMod-1.12.2-1.3.11.jar                    | None                                     |
       | LCH   | enderore                          | 1.12.2-v1.1              | Ender Ore-1.12.2-v1.1.jar                        | None                                     |
       | LCH   | endercrop                         | 1.12.2-1.6.0             | endercrop-1.12.2-1.6.0.jar                       | None                                     |
       | LCH   | enderiointegrationtic             | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | enderiobase                       | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | enderioconduits                   | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | enderioconduitsappliedenergistics | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | enderioconduitsopencomputers      | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | refinedstorage                    | 1.6.15                   | refinedstorage-1.6.15.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCH   | enderioconduitsrefinedstorage     | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | enderiointegrationforestry        | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | enderiointegrationticlate         | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | ftblib                            | 5.4.3.132                | FTBLib-5.4.3.132.jar                             | None                                     |
       | LCH   | enderiomachines                   | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | enderiopowertools                 | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                        | None                                     |
       | LCH   | everlastingabilities              | 1.5.1                    | EverlastingAbilities-1.12.2-1.5.1.jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | exchangers                        | 1.12.2-2.8               | Exchangers-1.12.2-2.8.jar                        | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCH   | fancylamps                        | 1.1.0                    | fancylamps-1.1.0.jar                             | None                                     |
       | LCH   | fasterladderclimbing              | 0.1-146                  | FasterLadderClimbing-1.12-0.1-146.jar            | None                                     |
       | LCH   | fastfurnace                       | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                     | None                                     |
       | LCH   | flopper                           | 1.0.3                    | Flopper-1.12.2-1.0.3.jar                         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | sonarcore                         | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                   | None                                     |
       | LCH   | fluxnetworks                      | 3.0.19                   | fluxnetworks-1.12.2-3.0.19-21.jar                | None                                     |
       | LCH   | foamfix                           | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                        | None                                     |
       | LCH   | forbidden_arcanus                 | 1.12.2-1.1.4             | forbidden_arcanus-1.12.2-1.1.4.jar               | None                                     |
       | LCH   | ftbutilities                      | 5.4.0.102                | FTBUtilities-5.4.0.102.jar                       | None                                     |
       | LCH   | ftbbackups                        | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.5.jar                  | None                                     |
       | LCH   | furnaceoverhaul                   | 2.2.0                    | FurnaceOverhaul-1.12.2-2.2.0.jar                 | None                                     |
       | LCH   | gravestone                        | 1.10.1                   | gravestone-1.10.1.jar                            | None                                     |
       | LCH   | hammercore                        | 2.0.5.0                  | HammerCore-1.12.2-2.0.5.0.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
       | LCH   | placebo                           | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                         | None                                     |
       | LCH   | hydrogel                          | 1.1.0                    | HydroGel-1.12.2-1.1.0.jar                        | None                                     |
       | LCH   | igwmod                            | 1.4.4-15                 | IGW-Mod-1.12.2-1.4.4-15-universal.jar            | None                                     |
       | LCH   | improvedbackpacks                 | 1.12.2-1.4.0.0           | ImprovedBackpacks-1.12.2-1.4.0.0.jar             | None                                     |
       | LCH   | infinitefluids                    | 1.2.0                    | infinitefluids-1.11-1.2.0.jar                    | None                                     |
       | LCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | jeiintegration                    | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar               | None                                     |
       | LCH   | jeivillagers                      | 1.0                      | jeivillagers-1.12-1.0.2.jar                      | None                                     |
       | LCH   | jecalculation                     | 1.12.2-3.2.0             | JustEnoughCalculation-1.12.2-3.2.0.jar           | None                                     |
       | LCH   | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
       | LCH   | laggoggles                        | FAT-1.12.2-4.8           | LagGoggles-FAT-1.12.2-4.8.jar                    | None                                     |
       | LCH   | lootcapacitortooltips             | 1.3                      | lootcapacitortooltips-1.3.jar                    | None                                     |
       | LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
       | LCH   | tbone                             | v1.6.8+mc1.12.2          | TBone-v1.6.8+mc1.12.2.jar                        | None                                     |
       | LCH   | metalchests                       | v6.1.0+mc1.12.2          | MetalChests-v6.1.0+mc1.12.2.jar                  | None                                     |
       | LCH   | modnametooltip                    | 1.10.1                   | modnametooltip_1.12.2-1.10.1.jar                 | None                                     |
       | LCH   | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
       | LCH   | mysticalagriculture               | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar             | None                                     |
       | LCH   | natura                            | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                       | None                                     |
       | LCH   | netherportalfix                   | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                | None                                     |
       | LCH   | nonausea                          | 1.0                      | NoNausea-MC1.12-1.0.jar                          | None                                     |
       | LCH   | samsocean                         | 1.0.2                    | OceanFloor-1.12.2-1.0.2.jar                      | None                                     |
       | LCH   | refinedstorageaddons              | 0.4.4                    | refinedstorageaddons-0.4.4.jar                   | None                                     |
       | LCH   | additionalstructures              | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar | None                                     |
       | LCH   | roost                             | 2.0.10                   | roost-1.12.2-2.0.10.jar                          | None                                     |
       | LCH   | rsgauges                          | 1.1.7                    | rsgauges-1.12.2-1.1.7.jar                        | ed58ed655893ced6280650866985abcae2bf7559 |
       | LCH   | simpledivegear                    | 1.1.1                    | SimpleDivingGear-1.1.1 mc 1.12.2.jar             | None                                     |
       | LCH   | simplequarry                      | 27r                      | SimpleQuarry-1.12.2-27r.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | solarpanelsreforged               | 1.12.2-001               | SolarPanelsReforged-1.12.2-1.0.jar               | None                                     |
       | LCH   | storagedrawersextra               | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar              | None                                     |
       | LCH   | storagetech                       | 6.0                      | StorageTech R6.0.jar                             | None                                     |
       | LCH   | tcinventoryscan                   | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar       | None                                     |
       | LCH   | thaumicjei                        | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                   | None                                     |
       | LCH   | thermalcultivation                | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | thermaldynamics                   | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | thermalinnovation                 | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | thermalsolars                     | 1.12.2 V1.9.5            | thermalsolars-1.12.2-1.9.5.jar                   | None                                     |
       | LCH   | tinymobfarm                       | 1.0.5                    | TinyMobFarm-1.12.2-1.0.5.jar                     | None                                     |
       | LCH   | tinyreactors                      | 1.12                     | tinyreactors-1.12-0.5.3.jar                      | None                                     |
       | LCH   | toastcontrol                      | 1.8.1                    | Toast Control-1.12.2-1.8.1.jar                   | None                                     |
       | LCH   | totemic                           | 1.12.2-0.11.6            | Totemic-1.12.2-0.11.6.jar                        | 21d11d7bf4d97b465382a1f95428029aac6daaea |
       | LCH   | underphangables                   | 1.0.0                    | underphangables-1.12.0-1.0.0.jar                 | None                                     |
       | LCH   | valkyrielib                       | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
       | LCH   | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
       | LCH   | vanillafix                        | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                         | None                                     |
       | LCH   | wailaharvestability               | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
       | LCH   | wanionlib                         | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                         | None                                     |
       | LCH   | llibrary                          | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | wings                             | 1.1.5                    | wings-1.1.5-1.12.2.jar                           | None                                     |
       | LCH   | bauble_wings                      | 1.0.0                    | wings-1.1.5-1.12.2.jar                           | None                                     |
       | LCH   | xaerominimap                      | 1.17.7                   | Xaeros_Minimap_1.17.7_Forge_1.12.jar             | None                                     |
       | LCH   | xaeroworldmap                     | 1.4.7                    | XaerosWorldMap_1.4.7_Forge_1.12.jar              | None                                     |
       | LCH   | xlfoodmod                         | 1.12.2-1.9.2             | XL-Food-Mod-1.12.2-1.9.2.jar                     | None                                     |
       | LCH   | yabba                             | 1.1.2.53                 | YABBA-1.1.2.53.jar                               | None                                     |
       | LCH   | zerocore                          | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                      | None                                     |
       | LCH   | nofog                             | 1.12.2-1.12.2-1.0.3.0    | NoFog-1.12.2b3.jar                               | 0bf221d944c89aaf3ccb7b8315148f222be50739 |
       | LCH   | eleccoreloader                    | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                      | None                                     |
       | LCH   | unidict                           | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                         | None                                     |
       | UD    | mobends_wings                     | 1.0.0                    | wings-1.1.5-1.12.2.jar                           | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      wings (wings-1.1.5-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      HCASM (HammerCore-1.12.2-2.0.5.0.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.65-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      LoadingPlugin (NoNausea-MC1.12-1.0.jar)
                                        lumien.nonausea.asm.ClassTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.20.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 1030/PCIe/SSE2'
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 433 names; 3383 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Simple Quarry (simplequarry) @27r
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
                               - craftingtweaksIntegration (Enabled/Not Forced)
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Totemic (totemic)
  Launched Version: forge-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: GeForce GT 1030/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: OceanWater-v1.0-1.11.zip, JSTR_Modded_Universal.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x AMD FX(tm)-8150 Eight-Core Processor

**Comment by Sunconure11** [comment]
You have too many blocks. Either remove some mods or installed JEID.
