### ISSUE TITLE
[1.12.2] Totemic breaks Potion-Core reach attribute fix.

### ISSUE THREAD

**Issue by Darkmega18** [TeamTotemic/Totemic#111]
I'm the author of a modpack, Timeless Technician. I've recently come across an issue where the special fix for the reach attribute being able to affect attack range is being broken by both this mod and random tweaks.

Basically things that increase block mining range like Corail tombstone reach, potioncores own reach potion, cyclic block reach enchant and the innate reach on tools like extra utils light sabers and random things phantom pickaxes can all contribute to being able to attack from further away.

Something in the mod seems to be cutting into the fix to enable that happening from functioning as my attack range despite being able to hit from this far:
![image](https://user-images.githubusercontent.com/8104689/80306613-b4f00980-8807-11ea-8c77-6b0ee7bd8da8.png)
reverts to normal range with totemic installed. :<

Is it possible to get someone to look into making this work and not break?

**Comment by ljfa-ag** [comment]
This is weird, I don't know which part of Totemic could be causing this.

**Comment by Darkmega18** [comment]
and it's been so long I likely have no clue what triggered it anymore. :V

**Comment by ljfa-ag** [comment]
Understandable :) I guess I will close this then.
