### ISSUE TITLE
Night vision fade effect starts too early

### ISSUE THREAD

**Issue by Nessworthy** [TeamTotemic/Totemic#112]
👋 

Just running off of SevTech here, it looks like the night vision fade effect starts at around 10 seconds. When using 1-3 enderman totem heads, it produces a really noticeable and distracting fade, then flashes back to full brightness every few seconds.

Would it be possible to use something like cubic easing, or to simply just lower the time before it starts fading?

With a screen at a reduced brightness level, you only really get about 5-7 seconds of this buff on a larger stacked totem :(

**Comment by ljfa-ag** [comment]
Usually the effect should refresh soon enough that no fade should be visible if you stay close to the Totem pole. But if the TPS drops low it might no longer be the case. I'm afraid there is no good way for us to fix that, I would suggest using a "no night vision flashing" mod.
