### ISSUE TITLE
Eagle Dance does not transform nearby parrots

### ISSUE THREAD

**Issue by mathfreak2** [TeamTotemic/Totemic#114]
In this specific case, I'm using Totemic as part of SevTech Ages, but this seems to be an issue with Totemic rather than the modpack as a whole, so I'm putting it here.

I successfully completed the Eagle Dance with a nearby parrots (it was around 7-8 blocks away). It did not transform. So, I tried looking up what the range on the Ceremony was, but I couldn't find anything more specific than "nearby". So, I tamed the parrot in order to bring it a bit closer, and I performed the ceremony, successfully, again, this time with the parrot literally right behind me. It still did not transform into an Eagle. 

I saw the little green particles around the Totem Base indicating a successful Ceremony, so I know I did it correctly, yet the parrot did not transform.

**Comment by ljfa-ag** [comment]
Can't reproduce this in SevTech Ages, it is working for me.
