### ISSUE TITLE
TOTEMIC MOD NOT WORKING

### ISSUE THREAD

**Issue by Kororororo** [TeamTotemic/Totemic#115]
I've playing Sevtech, at the stage where i need to do ceremonies mod does not work, the selector doesn't show up and i can't do anything. i tried downloading old versions but the problem is still the same.
The Mod just doesn't work and it's strange cause in youtubers gameplay it worked a couple months ago

**Comment by ljfa-ag** [comment]
In the Sevtech version that I am using it works fine. You need to sneak while playing an instrument in order to make the selector show up, maybe this is the problem?
