### ISSUE TITLE
[1.12.2] Whittling Knife removes entire Dynamic Tree

### ISSUE THREAD

**Issue by Garnin** [TeamTotemic/Totemic#117]
Using the Whittlingknife on Dynamic Trees results in a totem block at that location and the rest of the tree disappears with no wood drops or a tree falling effect. Is there a way to check if it is a dynamic tree and before placing the totem block break that block with an axe and then place a totem block there. That would in theory leave all other blocks beneath it available for further carving., as well as provide proper drops, and prevent having to break a tree and then replace it to create a totem.

Since totems don't drop as wood this would only be a minor abuse of low wood providing trees.

Possibly allow a config to allow the above behavior or instead do nothing when using the Whittling Knife.

Thanks for your time, love the mod.

**Comment by ljfa-ag** [comment]
That is a mod interaction that I will probably not fix for the 1.12 version. I don't know how Dynamic Trees is implemented.
