### ISSUE TITLE
[Suggestion] Adding modded wood support

### ISSUE THREAD

**Issue by PIPPIP5789** [TeamTotemic/Totemic#122]
Heyo! Hope everything going well so far with the 1.19 port.

I've loved playing with this mod for a while now, and while it's a ton of fun, there's one thing that's always been a bit of an issue for me: modded woods aren't supported. For instance, if you were to add on a mod like... I don't know, IC2 (rubber trees), there's no totem wood for rubber trees. While you might can explain away one or two trees, when playing with mods that add in a lot of different wood types (Biome's o' Plenty, Project: Vibrant Journeys, etc), it becomes immersion-shattering. Looking to modpacks, it becomes almost unbearably obvious. So, my request is pretty simple on the surface: could you please add in some kind of support for modded woods? Even if it's just a config.

Having looked through the code, I realize this would probably take an almost complete rework of the enum wood class, due to how you're handling wood choices, but I think it would be worth having some further configurability to work with other mods. I could try to code out something if that would be easier for you, if need be.

My final request is that this change is backported to previous versions like 1.12.2. I don't know your policy on supporting legacy versions, since you've moved from 1.12 to 1.19, but if there's any way to get this for the 1.12.2 release of the mod, that would be very appreciated, as a 1.12.2 mod and pack developer.

Thank you for your time, and regardless of your decision, I wish you the best of luck with the mod!

**Comment by ljfa-ag** [comment]
Thank you for your message :)

This is coming in version 1.19.2-0.12.5. Other mods will be able to add new wood types through the API, however, the ability to add them via config is worth looking into.

As for the 1.12.2 version, I am not planning to add new features to it, so I'm afraid I won't backport this.

**Comment by ljfa-ag** [comment]
Has been finally added :)
