### ISSUE TITLE
Help with Registering Custom Wood Types

### ISSUE THREAD

**Issue by NickIsCool45** [TeamTotemic/Totemic#127]
I have looked through the API and am confused, because I keep getting the error `Registry ResourceKey[minecraft:root / totemic:b_wood_type] does not exist!`

**Comment by ljfa-ag** [comment]
Hm, which Minecraft version are you using? It would be nice if you can give me the stack trace and the code that you are using for registering.

**Comment by ljfa-ag** [comment]
Unfortunately I can't really help you unless you give me more information. It is now possible to add custom wood types via config file, so maybe you can see if that works for you :)
