### ISSUE TITLE
Better sounds for the buffalo

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#13]
Currently, the buffalo use modified cow sounds. I suggest we give them actual buffalo calls.

Unfortunately, I do not have many good sources of such sounds, unless you are willing to dredge through sites like this: http://www.junglewalk.com/sound/Bison-sounds.htm

Or rip the sounds from youtube.

Wikipedia does not have any suitable sounds either, as they do sometimes have the sounds of various animals on their associated page.

**Comment by ljfa-ag** [comment]
Not the highest priority, but yeah, if we can find something that sounds good.

**Comment by Sunconure11** [comment]
- [ ] Buffalo Death Sound
- [ ] Buffalo Hurt Sound
- [ ] Buffalo Stampede sound? (this might require new AI...)
- [ ] Buffalo Call
- [ ] Buffalo Angered?
- [x] Buffalo Breathe (I think the current sounds might suffice for this)
- [ ] Buffalo Mating Call?
- [ ] Buffalo Idle
- [ ] Buffalo footsteps (might need a different sound for this)

**Comment by Sunconure11** [comment]
Other miscellaneous plans:
- [X] Change Baykok's bow texture, include a translucent overlay for arrows too so players can see where they are aiming (but other players won't)

I'll do this after I finish the next update to my pack.

I will also consider a remodel in the farther future.

**Comment by Sunconure11** [comment]
While this is a minor idea, @OreCruncher had some buffalo calls and what not in Dynamic Surroundings. Maybe ask him for some aid with this?

**Comment by Sunconure11** [comment]
While looking for sound sources for my own mod, I might have found places that would have such sounds. I will look through them on Wednesday.

**Comment by Sunconure11** [comment]
https://freesound.org/search/?q=bison&f=&s=score+desc&advanced=0&g=1

http://soundbible.com/tags-american-bison.html

https://www.youtube.com/watch?v=rkjMVMqRS_M

https://www.youtube.com/watch?v=Ng32W0BqGm4

Found a few sounds, more dredging is required, since they are american bison, and surprisingly, sound effects for them are scarce.

**Comment by ljfa-ag** [comment]
Any concrete ideas on which sound we could use, or will we never get to this?

**Comment by Sunconure11** [comment]
Not sure at the moment. ISP is being a PITA
