### ISSUE TITLE
damnation Wendigo

### ISSUE THREAD

**Issue by Giliod** [TeamTotemic/Totemic#16]
That it was possible to damn the player
![screenshot_2](https://cloud.githubusercontent.com/assets/16913459/16543763/5651de6e-410a-11e6-9a19-2056665631df.png)

**Comment by Sunconure11** [comment]
Becoming a wendigo was mentioned in a document of dumb ideas I had but eh, not sure if that will come to fruit anytime soon, if ever.

Another issue with a custom player model would be the fact that most armor would not render on it properly. This could possibly be solved by having it pop off the player, and give players with such models a passive armor bonus. This bonus could make up for the lack of armor.

But like I said, I doubt a wendigo is going to come to fruit.

**Comment by ljfa-ag** [comment]
Yeah it was an idea that was put on ice, at least for now. Although that would probably be a nice model.
