### ISSUE TITLE
The help with textures

### ISSUE THREAD

**Issue by Giliod** [TeamTotemic/Totemic#17]
You tried to contact other creators of mods what they have helped you?It is just interesting to me how soon we will see totems with muzzles of animals

**Comment by Sunconure11** [comment]
wat

**Comment by ljfa-ag** [comment]
What do you mean?
I was planning on making poles look different depending on carving but I'm not yet sure when I will get to that.

**Comment by Giliod** [comment]
Why don't you ask the help with model and texture of baykok of other creator of mods?As I have understood to you there isn't enough time

**Comment by Sunconure11** [comment]
I made the baykok model, and I plan on redoing it sometine in August. Plus if you are implying Baykok has not been implemented, it already has been.

Also, just because someone can make mods does not mean they can make models. Not every coder is an artist. Not every artist is a coder.

**Comment by Giliod** [comment]
And whether there are plans for mod this month? Also I wanted to offer idea with a falcon in whom it is possible to be installed and see him eyes as Brandon Stark from Game of thrones

**Comment by Sunconure11** [comment]
I don't think there are any major plans for the mod this month as far as I am aware. BTM and all of that jazz.

**Comment by ljfa-ag** [comment]
Closing this in favor of the other issue on that topic.
