### ISSUE TITLE
Buffalo Teeth texture is missing

### ISSUE THREAD

**Issue by ljfa-ag** [TeamTotemic/Totemic#2]

**Comment by Sunconure11** [comment]
Considered making it, but, I am not sure how to pull off teeth.

**Comment by Sunconure11** [comment]
I suppose I can see what I can do though.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/bhg91fkkamvpw73/bisontooth.png?dl=0

Remind me not to texture at 3 AM.

**Comment by Sunconure11** [comment]
I also tweaked the bison slightly, AGAIN.

https://www.dropbox.com/s/839lg0rch0ued9j/bison.png?dl=0

It should no longer have a weird black spot in the back of the head, which is very prominent in babies.

**Comment by ljfa-ag** [comment]
Ah thank you ^^
Yeah I noticed the black spot too. I would've just covered it up but well.
