### ISSUE TITLE
Tipi texture limits the mipmap level

### ISSUE THREAD

**Issue by mezz** [TeamTotemic/Totemic#20]
`textures/blocks/tipi.png` is 40x40 pixels, which is not a power of 2. 
This limits the mipmap level of the texture atlas, leading to ugly artifacts in distant textures.
Please make this texture 32x32 or 64x64 to fix this issue for BTM.

**Comment by ljfa-ag** [comment]
Hm, I saw that mentioned in the log, but I did not think that it would be problematic
