### ISSUE TITLE
Crash on startup, MC 1.10.2

### ISSUE THREAD

**Issue by xhaavardx** [TeamTotemic/Totemic#23]
Hi! I had a crash on startup that seems to be related to your mod.
I hope you can make some sense out of it. The easiest solution for me would be to remove your mod, but I still want to keep it in my setup, so that's why I'm contacting you.

My setup is:
- Minecraft 1.10.2
- Forge 12.8.1.2014
- Totemic 0.7.7

Here is the most relevant bit I could find:

> java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
>         at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:434)
>     at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:800)
>     at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:250)
>     at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:153)
>     at totemic_commons.pokefenn.ModBlocks.init(ModBlocks.java:59)
>     at totemic_commons.pokefenn.CommonProxy.preInit(CommonProxy.java:32)
>     at totemic_commons.pokefenn.ClientProxy.preInit(ClientProxy.java:40)
>     at totemic_commons.pokefenn.Totemic.preInit(Totemic.java:48)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

and here is the [crash log](https://paste.ee/p/TEj0z)

**Comment by Sunconure11** [comment]
You hit the ID limit. You might want to remove some unused mods.

**Comment by ljfa-ag** [comment]
Does it work if you remove some other mod that adds blocks? It seems like there are too many blocks.

**Comment by ljfa-ag** [comment]
Apparently it is not a problem with the mod, but rather something that can happen if you have too many mods in a pack, or mods that are wasteful with block IDs.
