### ISSUE TITLE
Remodel Baykok

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#25]
This is just a reminder to myself to do this when I am free enough, now that BTM is over.

Also a reminder to possibly tweak buffalo slightly (add udders)

**Comment by Sunconure11** [comment]
Buffalo with udders:

https://www.dropbox.com/s/2l87wz6ldwddl9p/new%20buffalo.zip?dl=0

**Comment by Sunconure11** [comment]
Sleep schedule is coming back on track. Expect it within a week or so. Afterwards, this thread will be closed.

**Comment by Sunconure11** [comment]
Its in the works, but sleep is still horrifyingly screwed. For now, I'm basing the headdress off of the Tzitzimitl from DiversityCraft with some minor additions.

https://www.dropbox.com/s/qofdty3jwbinepj/Screenshot%202016-08-29%2013.31.46.png?dl=0

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/mwufg6i9jj3zuwt/Screenshot%202016-09-06%2012.00.52.png?dl=0

Texturing begins tomorrow

**Comment by ljfa-ag** [comment]
Looks nice so far. But try to be more economical with the texture sheet.

**Comment by Sunconure11** [comment]
Texturing to continue on the weekend. The legs have been finished (aside from the fact that they will be greyscaled and given noise after I finish texturing the entire model). If greyscaling looks bad, I will just use the colors from the vanilla skeleton instead.

**Comment by Sunconure11** [comment]
Successfully remodelled and retextured. Awaiting implementation.

https://www.dropbox.com/s/u1zly4ejwc52s0n/baykoknew.zip?dl=0

**Comment by ljfa-ag** [comment]
Alright, thanks. Since at least 3/4 of the texture was unused, I cut the texture size in half for now.
