### ISSUE TITLE
Add support for new vanilla arrows and modded arrows

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#26]
Vanilla arrows: Spectral arrows and tipped arrows

Modded arrows: Bullseye and Quark both have arrows that might fit in well

**Comment by ljfa-ag** [comment]
The bow can already shoot all types of vanilla arrows, and it should work with modded arrows as well.

**Comment by Sunconure11** [comment]
Can confirm this. Closing.
