### ISSUE TITLE
Random ideas from IRC

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#28]
As the mod definitely needs new content in the future, there was some discussion in the IRC about it.

So far, only one thing has been definitively agreed upon, but this list will serve as a log for that for now.

Edit on 8/30/2016: More things have been discussed
- [x] Buffalo Totem (Provides haste) (Code done, waiting approval)
- [ ] Mob that automates totems in place of the player (8/30/2016) (Not fully fleshed out)
- [ ] Properties based on the material of the totem (8/30/2016)
- [x] Fix possible latency issue relating to totems (8/30/2016) (Needs more investigation)
- [x] Actual totem models (8/30/2016) (#50) (Might require massive changes)
- [x] A way to carry totem benefits (8/30/2016) (https://github.com/TeamTotemic/Totemic/issues/30) (In progress as of 12/9/2016) (Code done, textures to be done soon)
- [x] Fish totems (8/30/2016) (https://github.com/TeamTotemic/Totemic/issues/29)
- [x] Rabbit totem (provides luck) (8/30/2016)
- [ ] Quests for items to boost totems (8/30/2016)
- [x] Bear Totem (undecided buff) (8/30/2016, 9/4/2016)
- [x] "sun u loser pls finish up baykok soon everyone probably thinks ur lazy" Sunconure11's Mind, 2016

**Comment by Sunconure11** [comment]
Was the supposed latency issue ever fixed?

**Comment by ljfa-ag** [comment]
I don't know, I never got any details on that. I'll just tick it off.
