### ISSUE TITLE
Aquatic Totems

### ISSUE THREAD

**Issue by Divineaspect** [TeamTotemic/Totemic#29]
All of these would provide some degree of water breathing

Squid:  also removes blindness, as squids are the ink source.
Fish: also provides fishing luck
Salmon: also provides a jump boost, including when swimming upwards in water
Blowfish: provides poison and thorns effect

**Comment by ljfa-ag** [comment]
The Rabbit effect already gives jump boost, and the Pig effect gives luck which I believe also works for fishing.

I don't think I'll be adding more fish related Totem effects for now.
