### ISSUE TITLE
Medicine Bags

### ISSUE THREAD

**Issue by Divineaspect** [TeamTotemic/Totemic#30]
The Medicine bag allows you to carry a totem benefit with you, it's medicine, and use it later.

**Comment by ljfa-ag** [comment]
It is almost done, just need to wait for @Sunconure11 to make the textures.

**Comment by Sunconure11** [comment]
Give me a few days and I will do it. Sleep is getting better, but I'm trying to recover from the aftermath of a fucky sleep schedule.

**Comment by Sunconure11** [comment]
Textures are done, it should be ready for merging, though there appears to be a conflict that needs resolving.

**Comment by ljfa-ag** [comment]
That should be done now.
