### ISSUE TITLE
Shearing Red Cedar Leaves Bug

### ISSUE THREAD

**Issue by jawsawn** [TeamTotemic/Totemic#34]
It drops shears when you shear the cedar leaves, the shears are gone when you pick them up.

Also using your mod in Skyexchange modpack. I find it really innovative and interesting so I wanted to showcase it. So what is in the future of Totemic? At least make the jingle skirt jingle when you walk :P

**Comment by ljfa-ag** [comment]
Woops. Stuff you don't notice when testing in creative mode ^^

**Comment by jawsawn** [comment]
Do you have plans to update and add more things to this mod?

**Comment by ljfa-ag** [comment]
Yes, there are some ideas and new stuff in the making right now.
