### ISSUE TITLE
Botania easter egg

### ISSUE THREAD

**Issue by lilmoefow** [TeamTotemic/Totemic#35]
Is it necessary??  Yeah I get that you guys want to have fun and all, but is it possible to remove this or change it on my end?  Trying to make a modpack for my server group to host on Curse, and I already know that this name change at the top is going to cause a lot of confusion.  

If you are not sure what im referring to, it is the interaction between botania and totemic that changes "Minecraft 1.10.2" to "Floweycraft 1.10.2" 

Thanks for any help you can provide on this :)

**Comment by ljfa-ag** [comment]
I suppose I can add a config option for it. It does not happen every time so I thought it would be fine.

**Comment by lilmoefow** [comment]
it is a funny little easter egg, just a little confusing at first.
