### ISSUE TITLE
Text formatting issue

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#4]
https://www.dropbox.com/s/92lv64zbehd3ys1/Screenshot%202015-11-08%2003.21.26.png?dl=0

I think this image speaks for itself.

You might also want to move the jingle dress to the totemic tab.

**Comment by ljfa-ag** [comment]
Hm, it barely did fit on my screen but it didn't overflow...I have to look into that

**Comment by ljfa-ag** [comment]
I can only imagine that some other mod slightly changes font rendering, or that it is slightly different across platforms. Does it also happen without any other mod installed?

I made the text a bit wider but it probably won't solve it.

**Comment by ljfa-ag** [comment]
I added a page break to that lexicon entry, which should fix this.
I hope this was the only page where you had this issue.
