### ISSUE TITLE
Possible incompatibility with Animania

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#45]
Due to the changes Animania makes to cows (completely revamps them and sets them as a different mob), it is incompatible with this mod. This should probably be rectified in future versions.

https://minecraft.curseforge.com/projects/animania

On a side note, a creative item that allows for instant completion of a ritual would be nice.

**Comment by capnkirok** [comment]
Well, you can enable vanilla animals in the Animania config... 

Or you could add compatibility with Animania cows.

Wouldn't it be cool if there was an 'EntityDictionary'?

**Comment by ljfa-ag** [comment]
Yeah, could be useful for cases like these ^^
