### ISSUE TITLE
[Feature idea] Totemic Villager

### ISSUE THREAD

**Issue by angelnc1989** [TeamTotemic/Totemic#48]
A villager that has a little area in the village with a tipi, maybe some musical instruments and he trades Buffalo Tooth/Hide for Emeralds (or if you want to be racist some kind of alcohol).

**Comment by ljfa-ag** [comment]
Sounds like a good idea

**Comment by Giliod** [comment]
I do not see any special shifts. Is the artist busy?

**Comment by Giliod** [comment]
Already a whole year has passed. But I did not see the volume totems:(

**Comment by ljfa-ag** [comment]
Yeah there was not much progress. Not sure if @Sunconure11 is busy, but I haven't laid the groundwork for new totem models in the code yet.

**Comment by Sunconure11** [comment]
I'm busy with the development of another mod (witchworks). I am also in the final stages of a move.

I could texture the villager if I find myself not busy.

As for models, I fear too much damage to my sleep has hampered my capacity for modeling. I am also not sure how to approach such models when it comes to textures.

**Comment by ljfa-ag** [comment]
Do you think you will manage to texture it before BTM (mid-November)?

**Comment by Sunconure11** [comment]
I should be able to.

**Comment by ljfa-ag** [comment]
Implemented. Texture might change later.
