### ISSUE TITLE
Buffaloes targeted by enemies

### ISSUE THREAD

**Issue by TheFurtivePygmy** [TeamTotemic/Totemic#49]
I was surprised to see skeletons sniping my penned buffaloes. I'm not sure this is intended. If it is, it's a problem because they need to be fenced in like any other passive mob and this leaves them defenseless to skeletons.

One solution might be to have them not targetable until toggled (without duration) with the war dance ceremony. Another would be a totem carving that makes them return to the totem if not in combat.

**Comment by ljfa-ag** [comment]
Yes this is intended. The simplest solution is making sure the area around the pen is well lit.

But I realize this behavior might be annoying. I'll think about your proposals.

**Comment by TheFurtivePygmy** [comment]
Thanks for your reply.

I found that even if they're not penned in, they don't defend themselves if attacked by skeletons. Zombies don't attack them at all. All of this is pretty unintuitive. I think a config option to disable any hostile mob attacks would be good in the short-term.

**Comment by Sunconure11** [comment]
What about a config option? IIRC though, the in-game book mentions their behavior, so perhaps it could change slightly depending on the configs.

**Comment by ljfa-ag** [comment]
I will probably do that.

**Comment by ljfa-ag** [comment]
Added the config option and made Buffaloes retailate.
