### ISSUE TITLE
Crashes upon trying to shift-click Whittling Knife

### ISSUE THREAD

**Issue by 062regrahc** [TeamTotemic/Totemic#5]
[crash-2015-12-29_16.45.30-client.txt](https://github.com/TeamTotemic/Totemic/files/74381/crash-2015-12-29_16.45.30-client.txt)

**Comment by ljfa-ag** [comment]
Oh I see. I was inadvertently using something that is only available on Java 8.
I will fix this but I would recommend anyway to use Java 8.
