### ISSUE TITLE
Add models/textures for carved totempole patterns

### ISSUE THREAD

**Issue by craft90** [TeamTotemic/Totemic#50]
For some reason when you use the whittling knife on wood you can either turn it into a totem base or a totem pole. None of the different patterns seems to have an effect.

**Comment by craft90** [comment]
OK. So I appears to get buffs from the totem pole even if it doesn't show any visible change.

**Comment by ljfa-ag** [comment]
You need to have a Totem Base at the bottom and Totem Pole blocks above that. Does it work that way?

**Comment by craft90** [comment]
Yes. Totembase+totem pole "work" in the way that you get buffs. However there's no visual change to said totem pole. So there's no way of knowing what you have carved aswell as not particularly visually pleasing, unlike how it was back in 1.7.10. It kinda just look like thinner, leafless tree.

**Comment by ljfa-ag** [comment]
You can find out what you carved by using the Totemic Staff.
But I would agree that being able to see different patterns would be better and make it look better. I haven't got around to adding that yet.

**Comment by craft90** [comment]
Ah okay, didn't know that. The mod has changed since I last played it so I don't understand all parts yet.

**Comment by ljfa-ag** [comment]
We finally have that.
![](https://cdn.discordapp.com/attachments/426877881810157580/432498407014137857/2018-04-08_13.13.52.png)

**Comment by WesCook** [comment]
Huzzah!  Nice work!
