### ISSUE TITLE
New option 

### ISSUE THREAD

**Issue by bob0bob** [TeamTotemic/Totemic#52]
Will your mod be compatible with Animania?   Default for that mod is to replace the vanilla animals, so your mod requires vanilla cow.  So you can use the two together.   in Animania, it does have the option to not replace vanilla cows, so you can have both.

Just wondering if you might be thinking about using Animania cows to perform the ceremony to change into buffalo.

**Comment by ljfa-ag** [comment]
I already added that. Provided nothing broke, the ceremony should work with Animania cows.
