### ISSUE TITLE
[suggestion] Burial Grounds Structure

### ISSUE THREAD

**Issue by stohun01** [TeamTotemic/Totemic#58]
A cluster of blocks that naturally generate on the surface identical to grass blocks. When broken they spawn an undead mob (maybe with a type of headwear so they don't burn in sunlight). They'd have the same mechanics as silverfish, attacking the mob results in surrounding undead waking up.

**Comment by ljfa-ag** [comment]
I'm not sure if that would fit with the rest of the mod. Also, I want to avoid worldgen.
