### ISSUE TITLE
[SUGGESTION] Bring back buffalo aging, but gate it behind a config

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#60]
Due to the lag issues it had in the past (I did not notice them), it should be ideally, put under a config, with a warning for it. Bald eagles should have something similar as well, IMO. Animal aging should be put under a config, which would be disabled by default. Perhaps this feature could be expanded a bit, with older animals giving more loot.

Due to the nature of aging, the config setting should have a few warnings.

**Comment by ljfa-ag** [comment]
The lag could probably be avoided by implementing it differently than before. Not sure how it would work with loot tables.

I removed it because I thought it was inconsistent with vanilla and not really adding anything to the gameplay.

**Comment by Sunconure11** [comment]
I see then.

**Comment by ljfa-ag** [comment]
Do you still think it makes sense?

**Comment by Sunconure11** [comment]
Eh, it's fine either way. I just thought it was an interesting mechanic
