### ISSUE TITLE
Totempedia is CC BY-NC-SA 3.0, which is not MIT.

### ISSUE THREAD

**Issue by asiekierka** [TeamTotemic/Totemic#61]
You might want to make this fact more clear to users.

(Please don't change the license to CC BY-NC-SA over it)

**Comment by asiekierka** [comment]
A good suggestion would be to either:

(a) split the Totempedia into a separate mod,
(b) make the Totempedia use something which is FOSS. Guide-API might be a good choice, taking into account the mod's theming?

I can do either for you, if you wish.

**Comment by ljfa-ag** [comment]
I also thought about this when I forked the mod. This is the header comment of some of these sources:
```
 * This class was created by <Vazkii>. It's distributed as
 * part of the Totemic Mod. Get the Source Code in github:
 * https://github.com/Vazkii/Botania
 *
 * Botania is Open Source and distributed under a
 * Creative Commons Attribution-NonCommercial-ShareAlike 3.0 License
 * (http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_GB)
```
I assumed there was some agreement between Vazkii and Pokefenn allowing him to distribute these classes under the MIT license, if they are supposed to be part of the Totemic mod. So I assumed it was fine as long as I did not take more code from Botania.

But yes, I planned to eventually switch to Guide-API, it is just not high on my priority list. If you have time to do it I would appreciate it.

**Comment by asiekierka** [comment]
>I assumed there was some agreement between Vazkii and Pokefenn allowing him to distribute these classes under the MIT license, if they are supposed to be part of the Totemic mod.

Well, if that agreement isn't publicly documented, that doesn't really help anyone.

If you planned to switch anyway, the point is moot - I'll look into it.

**Comment by Sunconure11** [comment]
@asiekierka @ljfa-ag Vazkii and Fenn are still in, well, Vazkii's discord. You can probably grab them there if you must deal with this.

**Comment by asiekierka** [comment]
Should I carry forward with the Guide-API switch?

**Comment by ljfa-ag** [comment]
Be my guest, if I don't get to it myself.

**Comment by Pokefenn** [comment]
@asiekierka @ljfa-ag Yeah, I asked Vazkii about using the lexica because I couldn't be bothered to try and write my own code. Vaz said in an old skype log that I was fine to use it, and neither of us were thinking about license stuff.

**Comment by ljfa-ag** [comment]
I see. Thanks for the clarification.

**Comment by ljfa-ag** [comment]
@asiekierka Have you already started working on this?

**Comment by asiekierka** [comment]
Everything else fell to the wayside in May - busy with another big project, sorry!

I'll be able to take a look at this in August, if nobody else does so before.

**Comment by ljfa-ag** [comment]
Yeah I will probably start if not finish it before then ^^

**Comment by ljfa-ag** [comment]
Maybe I should wait until modded Minecraft 1.13 is available and GuideAPI (or an alternative) is ported.

**Comment by asiekierka** [comment]
>modded Minecraft 1.13 is available

H e h

**Comment by ljfa-ag** [comment]
Honestly, who knows if whatever I'll use is going to be ported at all.

**Comment by ljfa-ag** [comment]
I guess this is not relevant anymore :)

**Comment by asiekierka** [comment]
`I'll be able to take a look at this in August, if nobody else does so before.`

Shit, sorry.
