### ISSUE TITLE
Support for modded woods for Totem Base and Totem Pole

### ISSUE THREAD

**Issue by asiekierka** [TeamTotemic/Totemic#62]
I'd like to contribute this feature, as it fits my modpack plans. Is it desirable for the project?

**Comment by ljfa-ag** [comment]
Yes, and I think this has been suggested before. It would tie in with reintroducing wood bonuses.

How would you imagine to implement it? Have it add a variant for every modded log and autogenerate textures, or add an API where mods can opt in?

**Comment by asiekierka** [comment]
The same way I do it in Charset - store every modded log in the item stack's NBT (and the block's tile entity) as the item stack representation of the log, and cache retextured JSON models to ensure fast rendering.

It'd be cool if I could use CharsetLib for this, but I'm not going to force a dependency on you so I'll just copy over the relevant code structures (not a lot of them).

**Comment by ljfa-ag** [comment]
Sounds good. Yeah I'd rather not have that dependency.

**Comment by Sunconure11** [comment]
If you must use that as a dependency, why not do it as an addon?

**Comment by asiekierka** [comment]
Doing it as an addon would be the best for both parties, I think. I'll look into it.

**Comment by ljfa-ag** [comment]
I doubt that this sort of thing would work well as an addon. Especially when I want to expose the pole's wood type in the API.

**Comment by asiekierka** [comment]
If you expose the wood type as the wood log's ItemStack, there's no problem for modded poles to do so. And if you want a modification like this, you'll kind of have to do that anyway.

**Comment by ljfa-ag** [comment]
I see, that would make sense.

**Comment by ljfa-ag** [comment]
I guess this is not relevant anymore for newer Minecraft versions, as new Wood Types can be added.
