### ISSUE TITLE
Destroying Tipi with Explosion Breaks the structure and leaves Ghost Blocks

### ISSUE THREAD

**Issue by Darkosto** [TeamTotemic/Totemic#63]
Hello!

If you blow up the bottom section of a Tipi, the top blocks are left as ghost blocks and nothing else can be placed. If, however, you place the explosion at the top of the Tipi the mechanic works correctly. 

Totemic: 0.10.2
Forge: 2624
Minecraft: 1.12.2

Thanks!
Darkosto

![image](https://user-images.githubusercontent.com/10309699/37256519-205d5f3c-2532-11e8-9724-d9807035a388.png)

**Comment by ljfa-ag** [comment]
Should be fixed in the next version.

**Comment by Darkosto** [comment]
Great, thank you for your help :)

**Comment by artdude543** [comment]
When is the next version planned to be released which will have this fix?

**Comment by ljfa-ag** [comment]
Hopefully within a week from now.
