### ISSUE TITLE
Information Request for Totempedia

### ISSUE THREAD

**Issue by Darkosto** [TeamTotemic/Totemic#64]
Is it possible to add into the book that the player needs to Shift-Click to begin ceremony. I've been watching and getting bug reports from multiple users telling me they could not get a ceremony started because they weren't aware of shift-clicking. 

I completely understand that players should exhaust all their options but it's something that might not occur to every player and makes the mod seem less accessible. I would hate for someone to get the point of a ceremony and give up on the mod because they were not quite sure of the keybindings :)

Thank you!
Darkosto

**Comment by ljfa-ag** [comment]
It is already mentioned in the "Performing Ceremonies" entry:

> To select and initiate your Ceremony, you must play up to 4 Instruments in their selector mode to a Totem Pole, every ceremony has a unique sequence of Instruments. To play an Instrument in selector mode, just play it normally *while sneaking*.

Additionally it is mentioned in the "Flute", "Rattle" etc. entries as well.

Some entries are a bit outdated or not very clear and could use a rewrite, but I don't know how I could make it clearer.

**Comment by Darkosto** [comment]
To be honest, highlighting the word Sneaking could solve this issue.

**Comment by ljfa-ag** [comment]
I can at least do that.

**Comment by Darkosto** [comment]
I appreciate it, thank you.

**Comment by ljfa-ag** [comment]
Another idea to make it more intuitive and improve the QoL would be displaying the selecting instruments in the HUD. I will get to that at some point.

**Comment by Darkosto** [comment]
That's a great idea, I think that should get users all the information they need :)

**Comment by AlienSteel** [comment]
Just as reflection, it took me a while to get it to work as well, even after having read this thread :-) 
There where two things making it a bit more troublesome. First is that you must not have a flute in your right hand while trying to use the drum (for buffalo ceremony) and the second was that you have to stop sneaking to get any Music to count.

I'm thinking of doing a Swedish translation and if so I can take a look att the wording in English as well if you like, unfortunately I don't know any other languages good enough for other translations.

**Comment by ljfa-ag** [comment]
A basic version of the selector HUD has been implemented.

If you or anyone has concrete suggestions on changes of wording in the Totempedia, please let me know.
