### ISSUE TITLE
Sugar Cane Growth Ceremony?

### ISSUE THREAD

**Issue by Darkosto** [TeamTotemic/Totemic#67]
Hello!

I know Sugar Cane will not grow with Bone Meal, but is it possible to allow the Growth Speed ceremony to affect it?

https://github.com/Darkosto/SevTech-Ages/issues/1077

If not, no worries! Just wanted to ask if you would consider it :)

Thanks!
Darkosto

**Comment by ljfa-ag** [comment]
Yes, I think I will add that.
