### ISSUE TITLE
[Bug] Wind Chime activation

### ISSUE THREAD

**Issue by jursamaj** [TeamTotemic/Totemic#68]
The Wind Chimes can't be activated while holding anything in the off hand.  Drums, Flutes, and Rattles are not affected.

**Comment by ljfa-ag** [comment]
I'm not sure if I can do anything about that, since this is how it works in vanilla.

**Comment by ljfa-ag** [comment]
Fixed in da29ef8b8421415a76e4712f1bf5f6900fe58a5c.
