### ISSUE TITLE
[Bug] Totem Pedia is blank?

### ISSUE THREAD

**Issue by Durzobl** [TeamTotemic/Totemic#69]
Hey guys, is anyone willing to lend me a hand? Running into an error using totemic on SevTech FTB modpack
the totempedia is blank and as a result I've got no clue in hell what I'm doing ;~;

SevTech Ages 3.0.4

**Comment by ljfa-ag** [comment]
I don't know what could cause that. Did you change any config option, or the language? Did you add or remove any mods?

**Comment by Durzobl** [comment]
Nope ☹.

Fixed it by replacing the mod in the pack with a newer version – you may wish to update the SevTech people that they’re copy is outdated

**Comment by ljfa-ag** [comment]
That's strange, I did not touch the Totempedia code at all in that update.
