### ISSUE TITLE
Spirit summoning rituals and the like

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#7]
We discussed this a bit on IRC a while back, do you think that after you finish stomping all of the bugs with 1.8, we could discuss this in more detail, and figure out what to add, and what not to do? By then, I should be a bit more free after finishing the milk module draft for Growthcraft.

**Comment by ljfa-ag** [comment]
Yup, we could do that

**Comment by Sunconure11** [comment]
Almost free, and I have been accumulating a few possible spirits from various native american groups that could be used. However, all of my ideas so far would count as bosses.

Baykok
Amarok
Wendigo

**Comment by ljfa-ag** [comment]
So I guess we should find out what benefits you could get from them. I don't really have an idea how they could be integrated.

**Comment by Sunconure11** [comment]
Baykok is a grim-reaper-esque figure that hunts warriors, using invisible arrows or a club to attack his victims. Baykok could be some kind of boss that drops something useful. Maybe some ingredient that allows for invisible arrows, or some fairly powerful weapon?

Amarok is said to attack and devour anyone who is foolish enough to walk alone at night, and hunts alone. However, there are tales of him granting boons of some kind. This wikipedia page has some examples: https://en.wikipedia.org/wiki/Amarok_(wolf)

Wendigo is a human that has transformed into a monster as a result of cannibalism. Maybe it could be implemented as some form of curse, since if I recall some of pokefenn's old plans, there was a plan for a "dark side", aka the withered totemists. Not sure if he is still doing that though.

**Comment by Sunconure11** [comment]
Also, there are at least several fairy-like spirits from various native american mythologies.

Here is an example:

https://en.wikipedia.org/wiki/Pukwudgie

**Comment by Sunconure11** [comment]
You know what, do you think it'd be be better to formulate these on Skype or something?

**Comment by ljfa-ag** [comment]
Yeah, or on IRC maybe

**Comment by Sunconure11** [comment]
Alright, there are some things I need to attend to first, then I'll come up with a rough draft. Also, can more than two instruments be used in a ceremony? That might be required for these ceremonies.

**Comment by ljfa-ag** [comment]
During startup? Yes. For selecting the ceremony? Currently not.

**Comment by Sunconure11** [comment]
Hm, so new instruments then. Even if they are as uncreative as more infused variants of each instrument.

**Comment by Sunconure11** [comment]
Alright, thought of one instrument already, even though its just a variant of the drum.

Water Drum: A drum created by filling the drum chamber with water to produce a unique resonant sound. Made using 5 clay, 1 water bucket, and 3 buffalo hide or leather.

https://en.wikipedia.org/wiki/Water_drum

**Comment by Sunconure11** [comment]
I think I'm going to work with ReForged a bit, as well as try to figure out more solutions to get around the 2 instrument per ceremony limitation, as I think the spirit summoning ceremonies should be a bit more complex.

What about some kind of "upgraded" (not sure how this would be done) totem base that allows for more than 2 instruments to be used in a ceremony, and thus, more complex ceremonies. Tiering might be the solution for this. We are likely still going to have to create new instruments though anyways.

**Comment by ljfa-ag** [comment]
I'm not sure. Will we need that many ceremonies right now?
The numbers can always be increased later when it is needed I guess.

**Comment by Sunconure11** [comment]
Hm, I do not have an idea set up for how many spirits, and such, ceremonies. I'm trying to figure that out but finding stuff suitable is painful. However, what kinds of things are you looking for? Maybe if I know what types of spirits you want to be able to summon, I can find them, and then discuss them on IRC

**Comment by ljfa-ag** [comment]
Some of the ones you mentioned above sound nice, like Baykok.

**Comment by Sunconure11** [comment]
I shall see when I can think of ceremonies. Does the order in which an instrument is played matter? Because if it does, it could make making new ceremonies easier and yet also harder.

I'll look at the 1.8 ceremonies, and see how some could be implemented with what we have. I have not been on 1.8 much yet, as I am waiting for all of the mods to update for my massive kitchensink magic modpack.

Edit: Hm, so it does matter what order I set up instruments in.

**Comment by Sunconure11** [comment]
Should we close this until you are motivated to mod again?

Edit: I'll just close it for now.
