### ISSUE TITLE
[Silly Suggestion] Parrot Dancing

### ISSUE THREAD

**Issue by tofof** [TeamTotemic/Totemic#71]
Trigger nearby tamed parrots dancing when instruments are used -- extending the vanilla's behavior with jukebox blocks and music disks.

**Comment by ljfa-ag** [comment]
Or maybe during ceremonies (Eagle *Dance*). Why not.

**Comment by ljfa-ag** [comment]
I looked into it and it's hardcoded to only work for jukeboxes.
