### ISSUE TITLE
Console Spam of 0.0

### ISSUE THREAD

**Issue by tjsd** [TeamTotemic/Totemic#73]
Hello!
In sevtech ages I have an issue where people get totem effects the console of the server constantly spams 0.0. I cant even type in console and the log files of the server grows.
Is it maybe some debug info or?
SevTech v3.0.6
Forge 2651
Totemic-1.12.2-0.10.3.jar

It looks like this:
`0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0`

**Comment by Pokefenn** [comment]
I can't see any points in the code where System.out or the Logger is being used. Ljfa may know about this, but maybe this could be another mod interacting?

**Comment by ljfa-ag** [comment]
Does that only happen on the server or in singleplayer as well? Does it happen with all effects or only some?

**Comment by tjsd** [comment]
I havent tested it it in singleplayer. I only see it on the server.

**Comment by tjsd** [comment]
Also its a big modpack, it could be another mod interaction. I haven't tested it with totemic as the only mod.

**Comment by ljfa-ag** [comment]
It's not happening for me on SevTech. Are you sure that it only occurs when people get totem effects?

**Comment by tjsd** [comment]
No I am not. I have tested it with a different user in a different area and he put up a totem and it did not start spamming the console with the 0.0. So it must be something else in the other players chunk that does it. I guess we have to research it further to figure out what mod does this. Sorry for the false bug repport!

**Comment by tjsd** [comment]
The reason I suspected Totemic is that when that players area is unloaded the issue doesnt happen. I went to his chunks and the issue started. The only messeage I saw in the console was something is affected by totemic buff. This player has built a bridge and the pillars of the bridge is all Speed III totems. And I got the issue as soon as I got in range of that bridge. Its maybe 20 speed III totems. Could it be specific to the ammount of totems and overlapping buffs?

**Comment by ljfa-ag** [comment]
I doubt that, I really don't know where it would come from. What if you remove the pillars of the bridge?

**Comment by tjsd** [comment]
[15:05:24] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: <ToAsgaard> kk, im nearing my base
[15:05:36] [Server thread/WARN] [net.minecraft.world.WorldServer]: Keeping entity totemic:buffalo that already exists with UUID 8053a570-f2aa-4945-ae79-6d0cace1cf1f
> 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

**Comment by tjsd** [comment]
its very strange

**Comment by ljfa-ag** [comment]
I'm convinced that this does not come from Totemic. Sorry.
