### ISSUE TITLE
Mandan Buffalo Dance

### ISSUE THREAD

**Issue by OriginalSuperGumby** [TeamTotemic/Totemic#74]
First time this dance worked fine - two of four nearby cows converted. Second time no cows converted. Third time nada. There is no fourth time as I cannot get the dance to start at all. The war dance and Imbue flute dance both work fine - multiple times in a row.  I think there may be a problem with the chimes and their auto-ringing -maybe that's throwing off the start sequence?
Is there some way to cancel and reset everything to their beginning states?

**Comment by Pokefenn** [comment]
The chimes have to be shift + right clicked in order for their selector to work, so their playing wont be messing with the selector of the buffalo dance.
What version are you playing on?
And try left clicking with the Totemic Staff on the Totem Base to reset the block, and try it again.

**Comment by OriginalSuperGumby** [comment]
I was indeed shift-clicking the chime. I got it to work by hitting a different chime. I suspect the first chime is one square too far away. All instruments have to be within two squares horizontally?

**Comment by ljfa-ag** [comment]
No, the range should be farther than that. Maybe the other chime was closer to a different pole? Instruments only play to the nearest one.

**Comment by OriginalSuperGumby** [comment]
That makes sense. I have three poles in close proximity. Lesson learned thanks!
