### ISSUE TITLE
Infused flute doesn't make hippocampi follow.

### ISSUE THREAD

**Issue by mser7** [TeamTotemic/Totemic#75]
Infused flute seems to ineffective against Ice and fire's hippocampus, despite they have a follow ai when certain item is held, it does work on animania's hedgehog and ferret with their weird following item.

**Comment by mser7** [comment]
also, it work on Ice and fire mod's snow villagers

**Comment by ljfa-ag** [comment]
Their path navigator is not PathNavigateGround. I think fixing this would be too complicated and not worth it.

**Comment by mser7** [comment]
maybe i can contact the i/f creator to add the infused flute as a following item for them.
