### ISSUE TITLE
Feature Request: Wide Gates for Buffalo

### ISSUE THREAD

**Issue by ghost** [TeamTotemic/Totemic#78]
I'm keeping my Buffalo fenced, like my other animals, but they can't fit through a normal fence gate. Could you make a double-sized fence gate, or rather, a half-fence-gate that works like a door? You could put two side-by-side for a double-wide gate.

**Comment by ljfa-ag** [comment]
You should be able to get them through if you put two fence gates next to each other.

**Comment by ljfa-ag** [comment]
Justed tested it, two fence gates next to each other work.
