### ISSUE TITLE
Feature Request: Disabling individual ceremonies via config

### ISSUE THREAD

**Issue by MBlacktalon** [TeamTotemic/Totemic#79]
Hi folks. I'm looking at adding this mod to a pack I'm working on, and it'd be great if it were possible to disable specific ceremonies via the config. Specifically I don't want the player to be able to create zombie villagers, but it'd be a useful feature to be able to switch any ceremony on or off depending on personal preference.

**Comment by ljfa-ag** [comment]
Yeah I think we can do that for ceremonies that are not required for progression.
