### ISSUE TITLE
[Question] Torch

### ISSUE THREAD

**Issue by artdude543** [TeamTotemic/Totemic#80]
Ver: 0.11.0

Would it be possible to update the torch to break when lava comes near it like standard torches would?

Or is this an intended idea for the torch?

![image](https://user-images.githubusercontent.com/1885466/39270154-18711dd6-48cd-11e8-8135-cbad40e12118.png)

Thanks! 😄

**Comment by ljfa-ag** [comment]
Yeah, that's not intended.

**Comment by artdude543** [comment]
Thank you! 🙂

**Comment by Ozzymud** [comment]
I would like to comment that other crafted wood items in Minecraft vanilla do block lava, so I thought this was intentional. Ladders and signs will block lava, always have afaik and are made from just wood.

**Comment by ljfa-ag** [comment]
I just didn't think about how it would interact with lava or other fluids.

**Comment by Pokefenn** [comment]
The question comes down to whether or not we count this as a ladder like block, or a torch. It could easily pass as either. But since it's a light, it should be killed by water (lanterns are made for that), so I think that its good that it gets washed away now.
