### ISSUE TITLE
Missing localization for Red Cedar Sapling's tooltip

### ISSUE THREAD

**Issue by Lykrast** [TeamTotemic/Totemic#81]
![image](https://user-images.githubusercontent.com/8684850/39386241-fef061c0-4a73-11e8-95b1-88a31894017e.png)

Totemic version 1.12.2-0.11.1

**Comment by ljfa-ag** [comment]
@Pokefenn what was this tooltip supposed to say?

**Comment by Pokefenn** [comment]
"Created through Rite of Spring Ceremony"
