### ISSUE TITLE
Strobe Effect for Enderman Totem

### ISSUE THREAD

**Issue by PsyberMind** [TeamTotemic/Totemic#83]
I'm not sure that anything can be done about this, but I've noticed that there is a very annoying strobe effect when the enderman effect wears off.. I know this is likely the Vanilla potion effect wearing off, but with the enderman totem especially, if you don't have enough down, and you go out of range, or sometimes if the buff refresh is lagged, it will happen when you are standing right next to it. 

The biggest concern here is the fact that people who can experience epileptic seizures can be affected by this if it happens too frequently.

Maybe up the duration of the effect as a base, or.. honestly like I said, I don't know that anything can be done about this one.

**Comment by ljfa-ag** [comment]
I'll see what I can do, it's definitely problematic.

**Comment by ljfa-ag** [comment]
Hoping for MinecraftForge/MinecraftForge#4788 to get merged for a less hacky solution and more possibilities.
