### ISSUE TITLE
Strange compatibility issue with historicized medicine

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#85]
For some reason, the medicine man villager in this mod gets overriden by historicized medicine's plague doctor, causing some weirdness.

https://minecraft.curseforge.com/projects/historicized-medicine

**Comment by ljfa-ag** [comment]
What do you mean by "overridden"?

**Comment by Sunconure11** [comment]
Textures and trades

**Comment by ljfa-ag** [comment]
Issue was apparently on HistoricizedMedicine's end and resolved there.
