### ISSUE TITLE
Old-style cedar wood (White Cedar)

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#87]
Alright so an at-home sleep study I had done revealed the possibility of sleep apnea, and I will most likely have to go to a hospital at some point for a night to have a sleep study done there. This is probably why I've been so groggy and unproductive as of late.

Moving on though, I did think of some minor, decorative ideas, you could possibly tackle.

1. Return of old-style cedar wood: Why not add a crafting recipe to paint the red cedar planks to look like what they did on older versions of the mod? Maybe I'm the odd one out, but I liked them over the new ones TBH. The pink just seems... weird. Perhaps it could be applied to totems and what not too. Perhaps it could be created by adding orange dye to the wood?

2. Cedar workbenches, pressure plates, buttons, trapdoors, fences, doors, slabs, chests, and stairs: Basically wood anything made from cedar. Could be made from both the new red cedar and old-style.

3. You might want to make sure the Zaphkiel Waltz is compatible with Animania, since it alters most vanilla livestock.

**Comment by ljfa-ag** [comment]
1. I would rather have that as a different type of tree, maybe you could get the sapling with a crafting recipe from a Red Cedar sapling.

2. Yeah, see #76. Haven't gotten around to that yet.

3. I guess you mean Rite of Spring. I _think_ it should work but it needs to be tested.

Hope you will get a therapy or something to sort that out and sleep better.

**Comment by VincentLongiug** [comment]
I can't help but guessing people wanted to see a Cedar Door ![cedar door](https://user-images.githubusercontent.com/52882424/62708208-33dfb080-b9f3-11e9-8a3e-2739125f488e.png) and a Cedar Trapdoor ![cedar trapdoor](https://user-images.githubusercontent.com/52882424/62708214-35a97400-b9f3-11e9-95a0-71cee6d38e9e.png) like those ones (they're supposed to depict the Totem of your logo and a Medicine Wheel)

**Comment by ljfa-ag** [comment]
I guess this is not planned right now.

@VincentLongiug : I just stumbled on your answer, thank you for the door and trapdoor textures, these are just what I need right now :)
