### ISSUE TITLE
Stripped Red Cedar Wood randomly turning back

### ISSUE THREAD

**Issue by angelnc1989** [TeamTotemic/Totemic#89]
Minecraft 1.12.2
Forge 14.23.4.2707
Totemic 0.10.3/0.11.1
Singeplayer

I just noticed, that placed down Stripped Red Cedar Wood Blocks randomly turn back in Red Cedar Wood.
It doesn't matter whether they are placed down as Red Cedar Wood and stripped after or placed down as Stripped Red Cedar Wood.  
If they are stacked on top of each other only the bottom blocks tend to turn back.

**Comment by ljfa-ag** [comment]
This is actually an intended feature. It even says in the Totempedia that they will regrow their bark when placed above dirt.

That said, it seems like this doesn't have any gameplay purpose. I think I will remove this behavior at the latest when Minecraft 1.13 comes around, along with the bark stripper.

**Comment by Carnaxus** [comment]
You'll hinder a couple recipes in Sevtech: Ages if you remove Red Cedar's ability to be stripped.

I didn't actually know it regrew its bark, that's very useful for Sevtech and for Better With Mods by itself.

**Comment by ljfa-ag** [comment]
I won't remove Red Cedar's ability to be stripped, but Minecraft 1.13 adds stripped logs that can be made by using an axe. This is when I'm going to remove the bark stripper.

**Comment by Carnaxus** [comment]
Oh, I misread your comment then.  Sorry.

**Comment by angelnc1989** [comment]
Okay. My bad. Should have read the book.
