### ISSUE TITLE
Baykok model progress

### ISSUE THREAD

**Issue by Sunconure11** [TeamTotemic/Totemic#9]
It is time I begin progress on the model for baykok.

I'm thinking of basing his design off of the one for Shin Megami Tensei, but, there might be better designs.

Progress will begin on the weekend, there is some stuff I must do during the week.

**Comment by Sunconure11** [comment]
Looking on DA for ideas...

http://genzoman.deviantart.com/art/Baykok-436658322

http://adm-james.deviantart.com/art/Baykok-205848588

http://garylaibart.deviantart.com/art/Alphabestiary-Baykok-187773556

I think one of these three might work better for a possible design than the one from Shin Megami Tensei, as it has a rather weird color scheme.

**Comment by ljfa-ag** [comment]
Certainly something similar to a skeleton. With his bow it would fit into the game ^^

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/bmpgpo4r95zuoyo/Screenshot%202016-01-28%2001.43.00.png?dl=0

Never skip leg day. Still a work in progress, I'm starting from the bottom, and working my way to the top, as I want it to be similar to larger skeletal mobs, such as say, the Mutant Skeleton from Mutant Mobs.

**Comment by Sunconure11** [comment]
I'll port it to Tabula once the model is finished, and work on the texture maps there.

**Comment by Sunconure11** [comment]
I also have a design in mind. Basically, something like this:

http://adm-james.deviantart.com/art/Baykok-205848588

However, there would be a few variants used throughout combat. He will switch to his club for melee attacks, and switch to bow for ranged attacks.

**Comment by Sunconure11** [comment]
Would I need to model the bow too, or do you have that covered already?

**Comment by ljfa-ag** [comment]
I have that covered. But guess I would need textures for the bow item.
Right now he only uses his bow. Not sure if I can make him do both in a sensible way.

**Comment by Sunconure11** [comment]
Why not a bash attack with the bow?

**Comment by Sunconure11** [comment]
Sorry, I screwed up my sleep schedule slightly.

**Comment by Sunconure11** [comment]
Well, I got the start of the torso, but, I think it looks crummy so far. I'll take pictures later.

Large skeletal figures are hard, though I do have a weird idea to get the appearance of translucent skin.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/upg2of1i4sq2lft/Screenshot%202016-01-31%2021.28.52.png?dl=0

Here is the torso so far. Any advice? I have not begun on other parts of the body. I think I need some more input.

**Comment by ljfa-ag** [comment]
I guess he should have ribs as well, and the spine a bit more in the back.

Kinda difficult to judge when the textures and the translucency are not there yet ^^

**Comment by Sunconure11** [comment]
I won't be able to continue Baykok today. My room has an ant infestation. :/

**Comment by ljfa-ag** [comment]
o.O
well...no need to hurry

**Comment by Sunconure11** [comment]
Well the ants have been dealt with. But irregardless, I've been sleeping poorly. Again.

**Comment by Sunconure11** [comment]
Crap I forgot about continuing it. I'll see about working on the ribs within the next few days.

Also, Windows 10 decided to crap out on me so I had to reinstall it. However, the model was not lost.

**Comment by Sunconure11** [comment]
I realize it is not needed right away, but, I will model the boss some more this weekend.

**Comment by ljfa-ag** [comment]
Alright. And I will be less busy next week.

**Comment by Sunconure11** [comment]
Might not have enough time to do the model today, hopefully tomorrow I will. Stuff came up, me and some friends are going to do some... THINGS!

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/79p8unjxjx3zsbf/Screenshot%202016-02-14%2010.07.17.png?dl=0 Working on it, slowly.

**Comment by Sunconure11** [comment]
This model will take some time, due to the complexities associated with it.

**Comment by Sunconure11** [comment]
For now, I am ditching most of the rotation and offset shenanigans just so I can try and get the basic body shape.

**Comment by ljfa-ag** [comment]
Looks okay so far

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/lm1yetlcoa42vlb/Screenshot%202016-02-16%2015.47.58.png?dl=0

I think I will go with an emaciated look as opposed to fully skeletal, as pulling that off would be far too complicated.

**Comment by Sunconure11** [comment]
However, translucency might still be in my grasp.

**Comment by Sunconure11** [comment]
I'm going to start on the head.

https://www.dropbox.com/s/q9k79d869fle2vx/Screenshot%202016-02-20%2018.13.14.png?dl=0

oh god why

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/0uycghgk6rv5hxu/Screenshot%202016-02-20%2018.14.18.png?dl=0 A bit better.

**Comment by Sunconure11** [comment]
I'm going to do some heavy tweaking before I start on the texture map, and also I need to create the bow model.

**Comment by ljfa-ag** [comment]
Looks okay so far
A bow texture would also do instead of a detailed model. That might look a bit out of place next to Minecraft's regular bow.

**Comment by Sunconure11** [comment]
I'm sorry if this sounds like an excuse at this point but I had a skype convo on Sunday that lasted a little too long (around 1 AM to 6:30 AM EST) and fucked up my sleep schedule at this point. Also, when I get my sleep on track, are you going to handle the rendering of the item in hand, or should I create a 16x16 polygon or something in his hand for the item? I have the basic body plan set up, and I'm now going to tweak it heavily once I get my sleep together.

**Comment by ljfa-ag** [comment]
I'm going to handle the item rendering

**Comment by ljfa-ag** [comment]
I was planning to put Baykok into the next release but I guess this will still take a while

**Comment by Sunconure11** [comment]
Alright, my sleep is just getting back on track. Sorry.

I need to tweak the model a bunch, and then set up the texture. However, other stuff happened, including my messed up sleep cycle.

**Comment by Sunconure11** [comment]
Also, I am building the texture map.

**Comment by Sunconure11** [comment]
Texture map has been built. Final tweaking will begin in tabula tomorrow, followed by the addition of any other parts that need to be added. Afterwards, onwards, to texturing!

Also, I think you need to find another modeler, mainly one who does not have a screwy sleep schedule, just in case I cannot do a model, whether it be due to insomnia and a generally screwed up sleep schedule striking again, or you are requesting something too daunting.

In addition, I feel I am becoming less and less reliable for models and textures due to more involvement in other projects, and a tendency to screw up my sleep schedule.

**Comment by Sunconure11** [comment]
I'll begin this weekend, my sleep is still a bit flaky. In addition, I probably won't have time this week. I just had to fix a server using my modpack because Primitive Mobs screwed up attempting to despawn a mob, and some stuff with Growthcraft is taking up a bit of time.

**Comment by Sunconure11** [comment]
Can someone take on finishing up the model and texture for me? I'm feeling mentally exhausted as of late, and I need a break for a little bit to get myself together.

https://www.dropbox.com/s/lusjiuwym51g05n/baykok.zip?dl=0

Some info regarding the model can be found in that zip file.

**Comment by ljfa-ag** [comment]
Since I have no other choice, I will keep this model at least for now.
I'm currently experimenting with making the skin translucent and adding bones.

**Comment by ljfa-ag** [comment]
I think this effect looks pretty cool
![2016-04-01_15 39 14](https://cloud.githubusercontent.com/assets/3437174/14208495/fead212e-f81f-11e5-9197-56562445bc75.png)

**Comment by Sunconure11** [comment]
Looks like the boss is mostly done it seems. Closing for now, unless I need to redo it.
