### ISSUE TITLE
Totempedia crash with empty oredict entry

### ISSUE THREAD

**Issue by codetaylor** [TeamTotemic/Totemic#92]
### What

Removing the iron bells from the `<ore:bellsIron>` oredict entry causes a divide by zero error when using the remainder operator in [this line](https://github.com/TeamTotemic/Totemic/blob/527734541933567e6e23223d61489b2b1fcf4e00/src/main/java/pokefenn/totemic/totempedia/page/PageCraftingRecipe.java#L139) because `stacks.length` ends up being zero.

### Reproducing

1. Use CraftTweaker to remove the iron bells from the `<ore:bellsIron>` oredict entry
2. Browse to the Jingle Dress recipe in the Totempedia

### Crash

https://gist.github.com/codetaylor/c93a20f7d0a0e2c97106b9259c2a4886

### Versions

Minecraft: 1.12.2
Forge: 14.23.4.2705
Totemic: 1.12.2-0.11.2

**Comment by ljfa-ag** [comment]
Well, I guess it is to be expected that oredict recipes break when you remove all items from an oredict entry.

I'll see what I can do to improve the interactions with CraftTweaker in general.

**Comment by ljfa-ag** [comment]
The crash can be avoided by changing the recipe and making sure that the new recipe has no empty oredict entries. Apart from that, I will probably not add CraftTweaker support in the 1.12 version.
