### ISSUE TITLE
[Enhancement] Support for Fossils and Archeology

### ISSUE THREAD

**Issue by jman12351** [TeamTotemic/Totemic#95]
Seeing as Fossils and Archeology is updating to 1.12, I figured it could add some things to Totemic. You could have Buffalo and Eagle DNA, as well as totems for some of the Ice Age mobs (the Sabertooth, Mammoth, Irish Elk, etc.).

**Comment by Sunconure11** [comment]
Probably not going to happen, but no one has done an addon for this mod.

Maybe the woods could be supported for poles.

**Comment by ljfa-ag** [comment]
I guess it is on you if you want to add something since you know the mod better than me.

Custom wood support isn't a thing yet (#62), but probably will be in the 1.13 version.

**Comment by ljfa-ag** [comment]
Will probably not happen for the 1.12 version of Totemic.
