### ISSUE TITLE
Enchancement: Baby (Animal) Growth Ceremony

### ISSUE THREAD

**Issue by Guinaro** [TeamTotemic/Totemic#96]
I looked through the posted issues and didn't find this suggestion yet.

Since we have an increased growth rate for plants, I was wondering if we could have an increased growth rate for Baby Animals aswell.
Like double growth rate.

If possible a second tier Ceremony could be implemented that you need to complete in a set amount of time before the first Ceremony finishes so that you can quadruple the speed.

Or we could implement this as a ceremony where you constantly need to perform for the effect to happen. So if you want faster maturing animals, the only way is to continuously play on your instruments. So you need to dedicate your time to it.

Or a combination: a basic ritual where you can double the growth rate and leave it be and go do something else. Or if you continue playing after the standard ceremony you trigger a quadruple rate aslong as you keep on playing.

**Comment by ljfa-ag** [comment]
Yes, I think this is one of the things we have been planning.
This ceremony could then also affect eggs in place of the Zaphkiel Waltz.

**Comment by ljfa-ag** [comment]
Has (finally) been added in version 1.19.2-0.12.2.
