### ISSUE TITLE
Crazy idea

### ISSUE THREAD

**Issue by Giliod** [TeamTotemic/Totemic#99]
Please hold your rotten tomatoes. Isn't it the perfect model for Baykok? (You just need to modify the existing model a bit.)
![mutant-creatures-mod-4-750x404](https://user-images.githubusercontent.com/16913459/51184430-74b09480-18fe-11e9-998d-9032cf797ede.png)

**Comment by Pokefenn** [comment]
The model doesn't following the standard Minecraft convention for entities, it just would look out of place. Maybe Baykok needs a look at in the future, but it's definitely fine for now, and that model would not suit it.

**Comment by Sunconure11** [comment]
Ironically, I tried to model the old baykok model after that. It did not look that well.
